### ISSUE TITLE
no phone tone outgoing calls

### ISSUE THREAD

**Issue by nillebor** [arian-ota/ota#1]
last davinci LOS19 from 11.05.2022

no tone for free line or reception.
calls and incoming calls work

**Comment by nillebor** [comment]
there seems to be a problem with volte/vowlan.
if this is activated, there will be no outgoing ring signal. as soon as this is disabled  volte/vowlan and only the sim is called, it works normally

**Comment by ArianK16a** [comment]
Fixed with the next upcoming build.
