### ISSUE TITLE
build another ROM

### ISSUE THREAD

**Issue by Theangel256** [arian-ota/ota#15]
Sir, I understand that it is a hobby for you, but please you can try to building unofficial roms like PixelOS ir PixelExperience for Xiaomi 12 (cupid)? Honestly lineageOS has several details that I think nobody likes, how the unlimited photos function in Google photos does not exist, or the detection that it is a custom ROM in WhatsApp, or the lack of widgets on the lock screen, etc.

**Comment by Nabukodonosor** [comment]
Is this still true for the 21 version?

**Comment by arian-ota** [comment]
I don't plan on building anything but LineageOS for now.
