### ISSUE TITLE
Cupid Installation Process

### ISSUE THREAD

**Issue by arminolat** [arian-ota/ota#16]
Hello!

I would like to try this on my Xiaomi 12 (Cupid).
My bootloader is unlocked and I have TWRP recovery installed. 

Would anyone be kind enough to provide a step by step guide on how to install the latest version with nicore Gapps?

Thanks!

**Comment by freefd** [comment]
@arminolat, you could check this guide: https://forum.xda-developers.com/t/rom-13-unofficial-lineageos-20-for-xiaomi-12.4586861/
