### ISSUE TITLE
Camera doesn't work when unblock Camera access, build 2023-12-13

### ISSUE THREAD

**Issue by dmknght** [arian-ota/ota#19]
When i click `Camera` to take pictures, everything was black. It happened to the back camera only. Front camera is fine. To check and reproceduce problem, I did:
- Unblock Camera access
- Reboot
=> Camera worked
- Block Camera access
- Unlbock Camera access
=> Camera didn't work. It showed black only. Taking picture didn't work either. However, front camera worked fine.

**Comment by arian-ota** [comment]
Do you still have the issue? If yes, which version and device?

**Comment by dmknght** [comment]
> Do you still have the issue? If yes, which version and device?

Hello. I believe it was fixed. Sorry i forgot to close this issue. Closing it right now :D
