### ISSUE TITLE
the last update (july 1st 2022) refuse to install

### ISSUE THREAD

**Issue by erinarbleizez** [arian-ota/ota#2]
after a successfull download, taping install triger an immediat error in the notification. No specific error appear, just a "installation failed".

**Comment by erinarbleizez** [comment]
sideloading the update with adb and recovery seems to do the trick

**Comment by ArianK16a** [comment]
From which build are you coming?

**Comment by erinarbleizez** [comment]
I was up to date so the June 19th build

**Comment by ArianK16a** [comment]
Updating from that version should work. I have done it myself. If you aren't already on the newer build mind getting log?

**Comment by erinarbleizez** [comment]
sadly I have already done the update via sideloading and don't know how to access log. because It's the second time that problem occured (it also happened from June 18th build to June 19th) there is a high chance it occur again on the next.

I would be pleased to give logs when that happen if you tell me how to do.

**Comment by ArianK16a** [comment]
Just connect you device to a computer, enable adb in developer settings and then run adb logcat on a terminal on your computer.
