### ISSUE TITLE
unicorn lineage-21.0-20240318: persistent fingerprint white circle 

### ISSUE THREAD

**Issue by sk1r1** [arian-ota/ota#22]
Hello! At first, thank you for the builds, I really appreciate it!

Sometimes if I authenticate to some fingerprint secured app (i.e. mobile bank), the white circle still appears after authentication while my finger moves near fingerprint sensor, until reboot. I could not do the screenshot, because while it represents, the screenshot shortcut is not working. 

It is still possible to click through it, but it looks a bit weird.

**Comment by zzzz0317** [comment]
https://github.com/cupid-development/android_device_xiaomi_sm8450-common/issues/3
