### ISSUE TITLE
LOS 20 build for davinci?

### ISSUE THREAD

**Issue by nillebor** [arian-ota/ota#4]
the last updates for davinci is 20 - is that right? updated normally via ota?

Is this a typo or really the new version of google?

thank you for your support

**Comment by dennis-gruen** [comment]
It's really LOS 20.0 for davinci, just look at the changelog. Other roms for 20.0 are available by arian, too. Have not tested it yet, still on 19.1 and hoping for an maintenance update.
Anybody knows if you can dirtyflash from 19.1 to 20 on davinci? Are there problems with magisk/decryption/gapps?

**Comment by nillebor** [comment]
i tested it. it is a really early version and only conditionally recommended. a lot of work is currently being done on los20. dirty flash is not working.
tested with ArianLOS19.1 without gapps.

**Comment by dennis-gruen** [comment]
Thx for the input, I'll be sticking to 19.1 then since it's still my main phone ;)

**Comment by nillebor** [comment]
i'm also back on 19.1 and I'm hoping for a release with security update
