### ISSUE TITLE
Update GMS version

### ISSUE THREAD

**Issue by LXW-ei** [arian-ota/ota#7]
I used the September 15th version, no GMS, I can only use the 810

**Comment by embeddedskills** [comment]
bump on this,
can we dirty flash newer non gms versions?

**Comment by phyrz91** [comment]
Can we update the GMS version with a newer version in the VANILIA variant? Will we keep the Google app after such an update?

**Comment by arian-ota** [comment]
The GMS versions are not recommended anymore, it's preferred to install MindTheGapps like this: https://wiki.lineageos.org/gapps/

This should work on all builds of lineage-21 and above. GMS builds with MiuiCamera included will be done on an unregular schedule only and without update promises.
