### ISSUE TITLE
renoir: Recovery for LOS 19

### ISSUE THREAD

**Issue by samip5** [arian-ota/ota#9]
I'm unable to find the recovery file for LOS 19 on renoir?

**Comment by Enderw12** [comment]
@samip5 TWRP 3.7.0 worked for me. But i had issues with SafetyNet check. CTS profile match failed on every ROM (Including official MIUI). So i used PixelExperience ROM which does not have any issues with that for unknown reason.

hope this information would be useful for you. Good luck!
